stages:
  - test
  - build
  - deploy

variables:
  REGISTRY: "harbor.ecoit.vn"

default:
  tags:
    - x10-runner

backend-test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet test EvnHanoi.Digitization.slnx --configuration Release

backend-build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  before_script:
    - apt-get update && apt-get install -y docker.io
  script:
    - dotnet tool install -g Aspirate
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
    - cd Aspire/EvnHanoi.AppHost
    - aspirate build --non-interactive

backend-deploy:
  stage: deploy
  image:
    name: line/kubectl-kustomize:latest
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - if [ -f "$KUBERNETES_KUBE_CONFIG" ]; then cp "$KUBERNETES_KUBE_CONFIG" ~/.kube/config; else echo "$KUBERNETES_KUBE_CONFIG" > ~/.kube/config; fi
    - chmod 600 ~/.kube/config
  script:
    - kubectl cluster-info
    - cd Aspire/EvnHanoi.AppHost/overlays/production
    - kubectl apply -k .
