# =========================================================================
# Stage 1: Build the Angular SSR Application
# =========================================================================
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package dependency files
COPY package*.json ./

# Install npm dependencies (including devDependencies for build tools like Nx)
RUN npm ci

# Copy all application code
COPY . .

# Build the Angular application for production
RUN npx nx build admin-portal --configuration=production

# =========================================================================
# Stage 2: Serve the Built Application
# =========================================================================
FROM node:20-alpine AS runner

WORKDIR /app

# Copy the built output from builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

# Install only production dependencies to keep the image lightweight
RUN npm ci --omit=dev

# Set production environment variables
ENV NODE_ENV=production
ENV PORT=4000

# Expose server port
EXPOSE 4000

# Start the Node.js Express server generated by Angular SSR
CMD ["node", "dist/apps/admin-portal/server/server.mjs"]
