using DbUp.Engine;
using System;
using System.Data;

namespace EvnHanoi.Infrastructure.Migrations.DigitizationService;

/// <summary>
/// Sửa lệch schema: FILE_ATTACHMENT.ID (và FOLDER_DOCUMENTS.DOCUMENTID tham chiếu tới nó) được
/// 0001_Schema.sql tạo là NUMBER GENERATED BY DEFAULT AS IDENTITY, trong khi toàn bộ code phía C#
/// coi khoá này là UUID: <see cref="Guid"/> ở FileAttachment.Id, IFileAttachmentRepository.CreateAsync
/// tự sinh Guid.NewGuid() rồi INSERT tường minh, IVirtualFolderRepository.AddDocumentToFolderAsync
/// nhận Guid documentId, và OcrTaskMessage.FileId cũng là Guid. Hệ quả: mọi INSERT vào bảng này đều
/// chết trên schema NUMBER (ORA-01722 invalid number), nên endpoint upload của DigitizationService
/// chưa bao giờ ghi được DB.
///
/// Chuẩn hoá về quy ước khoá chính của project (BACKEND_GUIDELINES.md §2: PK là VARCHAR2(36) chứa
/// UUID, map qua GuidTypeHandler) thay vì đổi code sang NUMBER, vì phía code đã nhất quán dùng Guid
/// và FileId Guid còn đi xuyên qua RabbitMQ tới EquipmentService/NotificationService.
///
/// An toàn: cả FILE_ATTACHMENT và FOLDER_DOCUMENTS đều rỗng ở mọi môi trường (đường ghi duy nhất
/// chưa từng chạy được) — đã kiểm tra 2026-08-11 trên Oracle dùng chung 192.168.1.199/orcl: 0 dòng.
/// Nếu có dòng, Oracle sẽ báo ORA-01439 và migration dừng có kiểm soát: xử lý thủ công rồi chạy lại.
///
/// Rollback thủ công (DbUp không có down-migration):
///   ALTER TABLE FOLDER_DOCUMENTS DROP CONSTRAINT FK_FOLDER_DOC_DOC;
///   ALTER TABLE FOLDER_DOCUMENTS MODIFY (DOCUMENTID NUMBER);
///   ALTER TABLE FILE_ATTACHMENT  MODIFY (ID NUMBER);
///   ALTER TABLE FILE_ATTACHMENT  MODIFY ID GENERATED BY DEFAULT AS IDENTITY;
///   ALTER TABLE FOLDER_DOCUMENTS ADD CONSTRAINT FK_FOLDER_DOC_DOC
///       FOREIGN KEY (DOCUMENTID) REFERENCES FILE_ATTACHMENT(ID) ON DELETE CASCADE;
///   DELETE FROM SCHEMAVERSIONS WHERE SCRIPTNAME LIKE '%0003_FileAttachmentIdToVarchar36%';
/// </summary>
public class Migration0003_FileAttachmentIdToVarchar36 : IScript
{
    private const string IdType = "VARCHAR2(36)";

    public string ProvideScript(Func<IDbCommand> dbCommandFactory)
    {
        using var cmd = dbCommandFactory();

        string? ScalarText(string sql)
        {
            cmd.CommandText = sql;
            var value = cmd.ExecuteScalar();
            return value == null || value == DBNull.Value ? null : value.ToString();
        }

        void ExecuteNonQuery(string sql, params int[] ignoreErrorCodes)
        {
            try
            {
                cmd.CommandText = sql;
                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                foreach (var code in ignoreErrorCodes)
                {
                    if (ex.Message.Contains($"ORA-{code:D5}", StringComparison.OrdinalIgnoreCase))
                        return;
                }

                throw new Exception($"Failed executing SQL: {sql}. Error: {ex.Message}", ex);
            }
        }

        var fileAttachmentIdType = ScalarText(
            "SELECT DATA_TYPE FROM USER_TAB_COLS WHERE TABLE_NAME = 'FILE_ATTACHMENT' AND COLUMN_NAME = 'ID'");
        var folderDocumentIdType = ScalarText(
            "SELECT DATA_TYPE FROM USER_TAB_COLS WHERE TABLE_NAME = 'FOLDER_DOCUMENTS' AND COLUMN_NAME = 'DOCUMENTID'");

        // Idempotent: DB đã ở dạng VARCHAR2 (môi trường dev cũ tạo từ schema trước khi
        // 0001_Schema.sql được rebuild) thì không làm gì, DbUp vẫn ghi journal script này.
        if (!string.Equals(fileAttachmentIdType, "NUMBER", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(folderDocumentIdType, "NUMBER", StringComparison.OrdinalIgnoreCase))
        {
            return string.Empty;
        }

        // FK phải bỏ trước khi đổi kiểu 2 cột hai đầu quan hệ. ORA-02443: constraint không tồn tại.
        ExecuteNonQuery("ALTER TABLE FOLDER_DOCUMENTS DROP CONSTRAINT FK_FOLDER_DOC_DOC", 2443);

        // Cột IDENTITY không đổi được kiểu khi vẫn còn thuộc tính identity. ORA-30673: không phải
        // cột identity (DB đã bỏ identity từ trước).
        ExecuteNonQuery("ALTER TABLE FILE_ATTACHMENT MODIFY ID DROP IDENTITY", 30673);

        if (string.Equals(fileAttachmentIdType, "NUMBER", StringComparison.OrdinalIgnoreCase))
            ExecuteNonQuery($"ALTER TABLE FILE_ATTACHMENT MODIFY (ID {IdType})");

        if (string.Equals(folderDocumentIdType, "NUMBER", StringComparison.OrdinalIgnoreCase))
            ExecuteNonQuery($"ALTER TABLE FOLDER_DOCUMENTS MODIFY (DOCUMENTID {IdType})");

        // ORA-02275: FK trùng đã tồn tại (chạy lại sau khi lỗi giữa chừng).
        ExecuteNonQuery(@"
ALTER TABLE FOLDER_DOCUMENTS ADD CONSTRAINT FK_FOLDER_DOC_DOC
    FOREIGN KEY (DOCUMENTID) REFERENCES FILE_ATTACHMENT(ID) ON DELETE CASCADE", 2275);

        return string.Empty;
    }
}
