---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflowservice
  labels:
    app: workflowservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: workflowservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflowservice
    spec:
      containers:
      - name: workflowservice
        image: harbor.ecoit.vn/x10/backend/workflowservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: workflowservice-env
      terminationGracePeriodSeconds: 180