-- Migration for System Report Groups

-- 1. Drop existing dynamic report tables
DROP TABLE DYNAMIC_REPORTS;
DROP TABLE REPORT_GROUPS;

-- 2. Create REPORT_GROUPS table for System Report Groups
CREATE TABLE REPORT_GROUPS (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Code VARCHAR2(100) NOT NULL UNIQUE,
    Name VARCHAR2(255) NOT NULL,
    SortOrder NUMBER DEFAULT 0,
    Description VARCHAR2(1000) NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50),
    IsDeleted NUMBER(1) DEFAULT 0 NOT NULL
);

-- 3. Create REPORTS table for System Static Reports
CREATE TABLE REPORTS (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Code VARCHAR2(100) NOT NULL UNIQUE,
    Name VARCHAR2(255) NOT NULL
);

-- 4. Create Mapping tables
CREATE TABLE REPORT_GROUP_REPORTS (
    ReportGroupId NUMBER NOT NULL,
    ReportId NUMBER NOT NULL,
    PRIMARY KEY (ReportId, ReportGroupId),
    CONSTRAINT fk_rgr_rg FOREIGN KEY (ReportGroupId) REFERENCES REPORT_GROUPS(Id) ON DELETE CASCADE,
    CONSTRAINT fk_rgr_r FOREIGN KEY (ReportId) REFERENCES REPORTS(Id) ON DELETE CASCADE
);

CREATE TABLE REPORT_GROUP_UNITS (
    ReportGroupId NUMBER NOT NULL,
    UnitId NUMBER NOT NULL,
    PRIMARY KEY (UnitId, ReportGroupId),
    CONSTRAINT fk_rgu_rg FOREIGN KEY (ReportGroupId) REFERENCES REPORT_GROUPS(Id) ON DELETE CASCADE
);

-- 5. Seed 19 static system reports
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_YEAR', N'Báo cáo thống kê hồ sơ thiết bị theo năm');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_MONTH', N'Báo cáo thống kê hồ sơ thiết bị theo tháng');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_VOLTAGE_GRID', N'Báo cáo thống kê hồ sơ thiết bị theo lưới điện áp');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_EQUIPMENT', N'Báo cáo thống kê hồ sơ thiết bị theo thiết bị');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_ALLOCATION', N'Báo cáo hồ sơ thiết bị theo phân bổ hồ sơ');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_DOSSIER_TYPE', N'Báo cáo hồ sơ thiết bị theo loại hồ sơ');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_SHELF', N'Báo cáo hồ sơ thiết bị theo kệ lưu trữ');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_FLOOR', N'Báo cáo hồ sơ thiết bị theo tầng lưu trữ');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_BOX', N'Báo cáo hồ sơ thiết bị theo hộp lưu trữ');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_DOCUMENT_TYPE', N'Báo cáo hồ sơ thiết bị theo loại văn bản');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_STATION', N'Báo cáo hồ sơ thiết bị theo trạm');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_LINE', N'Báo cáo hồ sơ thiết bị theo đường dây');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_INPUT_OFFICER', N'Báo cáo hồ sơ thiết bị theo cán bộ nhập liệu');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_OPERATION_YEAR', N'Báo cáo hồ sơ thiết bị theo năm vận hành');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_OPERATION_TIME', N'Báo cáo hồ sơ thiết bị theo thời gian vận hành');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_MANUFACTURE_YEAR', N'Báo cáo hồ sơ thiết bị theo năm sản xuất thiết bị');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_BY_EQUIPMENT_STATUS', N'Báo cáo hồ sơ thiết bị theo tình trạng thiết bị');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_MOST_VIEWED', N'Báo cáo hồ sơ thiết bị được tra cứu nhiều nhất');
INSERT INTO REPORTS (Code, Name) VALUES ('REPORT_DOSSIER_GENERAL_INPUT', N'Báo cáo thống kê tổng hợp hồ sơ nhập liệu');

COMMIT;
