-- Migration for Report Unit Publish (Nhóm báo cáo đơn vị)
-- Cho phép Admin đơn vị cấu hình vai trò nào trong đơn vị được xem báo cáo cụ thể.

-- 1. Bảng cấu hình xuất bản báo cáo theo đơn vị
CREATE TABLE REPORT_UNIT_PUBLISH (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReportId NUMBER NOT NULL,
    UnitId NUMBER NOT NULL,
    IsPublish NUMBER(1) DEFAULT 0 NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50),
    CONSTRAINT fk_rup_report FOREIGN KEY (ReportId) REFERENCES REPORTS(Id) ON DELETE CASCADE,
    CONSTRAINT uq_rup_report_unit UNIQUE (ReportId, UnitId)
);

-- 2. Bảng mapping vai trò được phép xem báo cáo (UnitId/RoleId là FK phi logic tới
-- ORGANIZATION_UNIT/ROLE của IdentityService - cùng Oracle connection, khác logic domain)
CREATE TABLE REPORT_UNIT_PUBLISH_ROLE (
    PublishId NUMBER NOT NULL,
    RoleId NUMBER NOT NULL,
    PRIMARY KEY (PublishId, RoleId),
    CONSTRAINT fk_rupr_publish FOREIGN KEY (PublishId) REFERENCES REPORT_UNIT_PUBLISH(Id) ON DELETE CASCADE
);

COMMIT;
