---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipmentservice
  labels:
    app: equipmentservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: equipmentservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: equipmentservice
    spec:
      containers:
      - name: equipmentservice
        image: equipmentservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: equipmentservice-env
      terminationGracePeriodSeconds: 180