---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncservice
  labels:
    app: syncservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: syncservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncservice
    spec:
      containers:
      - name: syncservice
        image: harbor.ecoit.vn/x10/backend/syncservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: syncservice-env
      terminationGracePeriodSeconds: 180
