-- Alter UPLOAD_CONFIG table
ALTER TABLE UPLOAD_CONFIG DROP COLUMN ModuleCode;

ALTER TABLE UPLOAD_CONFIG ADD (
    Name VARCHAR2(200) DEFAULT 'Cấu hình upload' NOT NULL,
    OrganizationUnitId NUMBER NULL,
    IsActive NUMBER(1) DEFAULT 1 NOT NULL
);

ALTER TABLE UPLOAD_CONFIG ADD CONSTRAINT fk_upload_config_orgunit 
    FOREIGN KEY (OrganizationUnitId) REFERENCES ORGANIZATION_UNIT(Id) ON DELETE SET NULL;
