-- Migration to add IsActive column to ORGANIZATION_UNIT and ROLE tables
ALTER TABLE ORGANIZATION_UNIT ADD IsActive NUMBER(1) DEFAULT 1 NOT NULL;
ALTER TABLE ROLE ADD IsActive NUMBER(1) DEFAULT 1 NOT NULL;
