-- Dọn quyền xuất bản cũ trên DossierController; EquipmentService/NotificationService sẽ sinh lại qua DossierPublishController.

DELETE FROM PERMISSION_DETAIL
WHERE ControllerName = 'DossierController'
  AND ActionName IN ('CheckPublishViewPermission', 'Publish', 'Unpublish', 'Republish');

DELETE FROM PERMISSION_DETAIL
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_PUBLISH', 'DOSSIER_PUBLISH_PUBLISH_VIEW'));

DELETE FROM ROLE_PERMISSION
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_PUBLISH', 'DOSSIER_PUBLISH_PUBLISH_VIEW'));

DELETE FROM USER_PERMISSION
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_PUBLISH', 'DOSSIER_PUBLISH_PUBLISH_VIEW'));

DELETE FROM USER_GROUP_PERMISSION
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_PUBLISH', 'DOSSIER_PUBLISH_PUBLISH_VIEW'));

DELETE FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_PUBLISH', 'DOSSIER_PUBLISH_PUBLISH_VIEW');

COMMIT;
