-- Đổi mã quyền thao tác xuất bản: DOSSIER_PUBLISH → DOSSIER_PUBLISH_RELEASE

UPDATE PERMISSION
SET Code = 'DOSSIER_PUBLISH_RELEASE',
    Name = N'Xuất bản hồ sơ',
    Description = N'Tự động sinh: Cho phép xuất bản / hủy / tái xuất bản hồ sơ'
WHERE Code = 'DOSSIER_PUBLISH';

DELETE FROM PERMISSION_DETAIL
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_EDIT', 'DOSSIER_PUBLISH_MANAGE'));

DELETE FROM ROLE_PERMISSION
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_EDIT', 'DOSSIER_PUBLISH_MANAGE'));

DELETE FROM USER_PERMISSION
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_EDIT', 'DOSSIER_PUBLISH_MANAGE'));

DELETE FROM USER_GROUP_PERMISSION
WHERE PermissionId IN (SELECT Id FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_EDIT', 'DOSSIER_PUBLISH_MANAGE'));

DELETE FROM PERMISSION WHERE Code IN ('DOSSIER_PUBLISH_EDIT', 'DOSSIER_PUBLISH_MANAGE');

COMMIT;
