-- Migration: Thêm quyền xuất nhật ký hệ thống AUDIT_LOG_EXPORT

INSERT INTO PERMISSION (Id, Code, Name, Description, IsActive, CreatedBy)
SELECT 'audit_log_export_id',
       'AUDIT_LOG_EXPORT',
       N'Xuất nhật ký hệ thống',
       N'Tự động sinh: Xuất file Excel/CSV nhật ký audit',
       1,
       'SYSTEM'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM PERMISSION WHERE Code = 'AUDIT_LOG_EXPORT'
);

INSERT INTO ROLE_PERMISSION (Id, RoleId, PermissionId)
SELECT SYS_GUID(), 
       (SELECT Id FROM ROLE WHERE Code = 'ADMIN' AND ROWNUM = 1), 
       (SELECT Id FROM PERMISSION WHERE Code = 'AUDIT_LOG_EXPORT' AND ROWNUM = 1)
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM ROLE_PERMISSION
    WHERE RoleId = (SELECT Id FROM ROLE WHERE Code = 'ADMIN' AND ROWNUM = 1)
      AND PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'AUDIT_LOG_EXPORT' AND ROWNUM = 1)
)
AND (SELECT Id FROM ROLE WHERE Code = 'ADMIN' AND ROWNUM = 1) IS NOT NULL
AND (SELECT Id FROM PERMISSION WHERE Code = 'AUDIT_LOG_EXPORT' AND ROWNUM = 1) IS NOT NULL;

COMMIT;
