-- Soft delete support for organization units and users
ALTER TABLE ORGANIZATION_UNIT ADD IsDeleted NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE APP_USER ADD IsDeleted NUMBER(1) DEFAULT 0 NOT NULL;

CREATE INDEX IDX_ORG_UNIT_IS_DELETED ON ORGANIZATION_UNIT(IsDeleted);
CREATE INDEX IDX_APP_USER_IS_DELETED ON APP_USER(IsDeleted);
