-- Tách namespace phân quyền biểu mẫu EAV theo controller:
-- EavFormTemplateController → EAV_FORM_TEMPLATE_*
-- EavFormApprovalController → EAV_FORM_APPROVAL_*
-- EavCompletedFormController → EAV_COMPLETED_FORM_*

UPDATE APP_MENU
SET PermissionCode = 'EAV_FORM_TEMPLATE_VIEW'
WHERE Url = '/equipment/form-management';

UPDATE APP_MENU
SET PermissionCode = 'EAV_FORM_APPROVAL_VIEW'
WHERE Url = '/equipment/form-approval';

UPDATE APP_MENU
SET PermissionCode = 'EAV_COMPLETED_FORM_VIEW'
WHERE Url = '/equipment/completed-forms';

-- 1. Cặp EAV_FORM_TEMPLATE_APPROVAL_VIEW -> EAV_FORM_APPROVAL_VIEW
DELETE FROM ROLE_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW' AND ROWNUM = 1)
  AND RoleId IN (
      SELECT RoleId FROM ROLE_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1)
  );

UPDATE ROLE_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW' AND ROWNUM = 1)
  AND UserId IN (
      SELECT UserId FROM USER_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1)
  );

UPDATE USER_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_GROUP_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW' AND ROWNUM = 1)
  AND UserGroupId IN (
      SELECT UserGroupId FROM USER_GROUP_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1)
  );

UPDATE USER_GROUP_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM PERMISSION 
WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW'
  AND EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW');

UPDATE PERMISSION
SET Code = 'EAV_FORM_APPROVAL_VIEW',
    Name = N'Xem hàng chờ phê duyệt biểu mẫu',
    Description = N'Tự động sinh: Cho phép xem hàng chờ phê duyệt biểu mẫu EAV'
WHERE Code = 'EAV_FORM_TEMPLATE_APPROVAL_VIEW'
  AND NOT EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_VIEW');

-- 2. Cặp EAV_FORM_TEMPLATE_APPROVE -> EAV_FORM_APPROVAL_APPROVE
DELETE FROM ROLE_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE' AND ROWNUM = 1)
  AND RoleId IN (
      SELECT RoleId FROM ROLE_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1)
  );

UPDATE ROLE_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE' AND ROWNUM = 1)
  AND UserId IN (
      SELECT UserId FROM USER_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1)
  );

UPDATE USER_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_GROUP_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE' AND ROWNUM = 1)
  AND UserGroupId IN (
      SELECT UserGroupId FROM USER_GROUP_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1)
  );

UPDATE USER_GROUP_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM PERMISSION 
WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE'
  AND EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE');

UPDATE PERMISSION
SET Code = 'EAV_FORM_APPROVAL_APPROVE',
    Name = N'Phê duyệt / từ chối biểu mẫu',
    Description = N'Tự động sinh: Cho phép phê duyệt hoặc từ chối biểu mẫu EAV'
WHERE Code = 'EAV_FORM_TEMPLATE_APPROVE'
  AND NOT EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_FORM_APPROVAL_APPROVE');

-- 3. Cặp EAV_FORM_TEMPLATE_COMPLETED_VIEW -> EAV_COMPLETED_FORM_VIEW
DELETE FROM ROLE_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW' AND ROWNUM = 1)
  AND RoleId IN (
      SELECT RoleId FROM ROLE_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1)
  );

UPDATE ROLE_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW' AND ROWNUM = 1)
  AND UserId IN (
      SELECT UserId FROM USER_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1)
  );

UPDATE USER_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_GROUP_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW' AND ROWNUM = 1)
  AND UserGroupId IN (
      SELECT UserGroupId FROM USER_GROUP_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1)
  );

UPDATE USER_GROUP_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM PERMISSION 
WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW'
  AND EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW');

UPDATE PERMISSION
SET Code = 'EAV_COMPLETED_FORM_VIEW',
    Name = N'Xem danh sách form hoàn thành',
    Description = N'Tự động sinh: Cho phép xem danh sách biểu mẫu EAV hoàn thành'
WHERE Code = 'EAV_FORM_TEMPLATE_COMPLETED_VIEW'
  AND NOT EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_VIEW');

-- 4. Cặp EAV_FORM_TEMPLATE_MANAGE -> EAV_COMPLETED_FORM_MANAGE
DELETE FROM ROLE_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE' AND ROWNUM = 1)
  AND RoleId IN (
      SELECT RoleId FROM ROLE_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1)
  );

UPDATE ROLE_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE' AND ROWNUM = 1)
  AND UserId IN (
      SELECT UserId FROM USER_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1)
  );

UPDATE USER_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM USER_GROUP_PERMISSION 
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE' AND ROWNUM = 1)
  AND UserGroupId IN (
      SELECT UserGroupId FROM USER_GROUP_PERMISSION 
      WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1)
  );

UPDATE USER_GROUP_PERMISSION 
SET PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1)
WHERE PermissionId = (SELECT Id FROM PERMISSION WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE' AND ROWNUM = 1)
  AND (SELECT Id FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE' AND ROWNUM = 1) IS NOT NULL;

DELETE FROM PERMISSION 
WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE'
  AND EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE');

UPDATE PERMISSION
SET Code = 'EAV_COMPLETED_FORM_MANAGE',
    Name = N'Khóa / mở khóa biểu mẫu hoàn thành',
    Description = N'Tự động sinh: Cho phép khóa hoặc mở khóa biểu mẫu EAV hoàn thành'
WHERE Code = 'EAV_FORM_TEMPLATE_MANAGE'
  AND NOT EXISTS (SELECT 1 FROM PERMISSION WHERE Code = 'EAV_COMPLETED_FORM_MANAGE');

COMMIT;
