-- Seed default permissions for OPERATOR and USER groups (L3)

-- 1. Delete existing mappings for OPERATOR to prevent duplicate key
DELETE FROM PERMISSION_GROUP_PERMISSION 
WHERE PermissionGroupId = (SELECT Id FROM PERMISSION_GROUP WHERE Code = 'OPERATOR' AND ROWNUM = 1)
  AND PermissionId IN (
      SELECT Id FROM PERMISSION 
      WHERE Code IN ('VIEW_DASHBOARD', 'EQUIPMENT_VIEW', 'EQUIPMENT_MANAGE', 'DIGITIZATION_VIEW', 'DIGITIZATION_MANAGE', 'REPORT_VIEW', 'CATALOG_VIEW', 'SEARCH_DOSSIERS_BY_EQUIPMENT_VIEW', 'SEARCH_DOSSIERS_IN_WAREHOUSE_VIEW', 'AUDIT_LOG_VIEW')
  );

-- 2. Insert new mappings for OPERATOR
INSERT INTO PERMISSION_GROUP_PERMISSION (Id, PermissionGroupId, PermissionId)
SELECT SYS_GUID(), 
       (SELECT Id FROM PERMISSION_GROUP WHERE Code = 'OPERATOR' AND ROWNUM = 1), 
       p.Id
FROM PERMISSION p
WHERE p.Code IN ('VIEW_DASHBOARD', 'EQUIPMENT_VIEW', 'EQUIPMENT_MANAGE', 'DIGITIZATION_VIEW', 'DIGITIZATION_MANAGE', 'REPORT_VIEW', 'CATALOG_VIEW', 'SEARCH_DOSSIERS_BY_EQUIPMENT_VIEW', 'SEARCH_DOSSIERS_IN_WAREHOUSE_VIEW', 'AUDIT_LOG_VIEW')
  AND (SELECT Id FROM PERMISSION_GROUP WHERE Code = 'OPERATOR' AND ROWNUM = 1) IS NOT NULL;

-- 3. Delete existing mappings for USER to prevent duplicate key
DELETE FROM PERMISSION_GROUP_PERMISSION 
WHERE PermissionGroupId = (SELECT Id FROM PERMISSION_GROUP WHERE Code = 'USER' AND ROWNUM = 1)
  AND PermissionId IN (
      SELECT Id FROM PERMISSION 
      WHERE Code IN ('VIEW_DASHBOARD', 'EQUIPMENT_VIEW', 'CATALOG_VIEW', 'SEARCH_DOSSIERS_BY_EQUIPMENT_VIEW', 'SEARCH_DOSSIERS_IN_WAREHOUSE_VIEW')
  );

-- 4. Insert new mappings for USER
INSERT INTO PERMISSION_GROUP_PERMISSION (Id, PermissionGroupId, PermissionId)
SELECT SYS_GUID(), 
       (SELECT Id FROM PERMISSION_GROUP WHERE Code = 'USER' AND ROWNUM = 1), 
       p.Id
FROM PERMISSION p
WHERE p.Code IN ('VIEW_DASHBOARD', 'EQUIPMENT_VIEW', 'CATALOG_VIEW', 'SEARCH_DOSSIERS_BY_EQUIPMENT_VIEW', 'SEARCH_DOSSIERS_IN_WAREHOUSE_VIEW')
  AND (SELECT Id FROM PERMISSION_GROUP WHERE Code = 'USER' AND ROWNUM = 1) IS NOT NULL;

COMMIT;
