using System;
using System.Data;
using DbUp.Engine;

namespace EvnHanoi.Infrastructure.Migrations.IdentityService;

/// <summary>
/// Creates the persistent login history displayed in the SSO audit tab.
/// </summary>
public sealed class Migration0055_CreateSsoLoginHistoryTable : IScript
{
    public string ProvideScript(Func<IDbCommand> dbCommandFactory)
    {
        using var command = dbCommandFactory();

        try
        {
            command.CommandText = @"
                CREATE TABLE SSO_LOGIN_HISTORY (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    USER_ID VARCHAR2(36) NULL,
                    USERNAME VARCHAR2(200) NOT NULL,
                    FULL_NAME VARCHAR2(255) NULL,
                    ACTION VARCHAR2(50) DEFAULT 'SSO_LOGIN' NOT NULL,
                    RESOURCE_TYPE VARCHAR2(100) DEFAULT 'SSO' NOT NULL,
                    RESOURCE_NAME VARCHAR2(255) DEFAULT 'Cổng SSO EVNHANOI' NULL,
                    LOGIN_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    DETAILS CLOB NULL,
                    IP_ADDRESS VARCHAR2(64) NULL,
                    STATUS_CODE NUMBER(5) NULL,
                    IS_SUCCESS NUMBER(1) DEFAULT 1 NOT NULL,
                    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
                    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    CONSTRAINT FK_SSO_LOGIN_HISTORY_USER
                        FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID) ON DELETE SET NULL,
                    CONSTRAINT CK_SSO_LOGIN_HISTORY_SUCCESS CHECK (IS_SUCCESS IN (0, 1)),
                    CONSTRAINT CK_SSO_LOGIN_HISTORY_DELETED CHECK (IS_DELETED IN (0, 1))
                )";
            command.ExecuteNonQuery();
        }
        catch (Exception ex) when (ex.Message.Contains("ORA-00955", StringComparison.OrdinalIgnoreCase))
        {
            // The table already exists in this database.
        }

        CreateIndexIfMissing(
            command,
            "IDX_SSO_LOGIN_HISTORY_LOGIN_AT",
            "CREATE INDEX IDX_SSO_LOGIN_HISTORY_LOGIN_AT ON SSO_LOGIN_HISTORY(LOGIN_AT)");
        CreateIndexIfMissing(
            command,
            "IDX_SSO_LOGIN_HISTORY_USERNAME",
            "CREATE INDEX IDX_SSO_LOGIN_HISTORY_USERNAME ON SSO_LOGIN_HISTORY(USERNAME)");
        CreateIndexIfMissing(
            command,
            "IDX_SSO_LOGIN_HISTORY_USER_ID",
            "CREATE INDEX IDX_SSO_LOGIN_HISTORY_USER_ID ON SSO_LOGIN_HISTORY(USER_ID)");

        return string.Empty;
    }

    private static void CreateIndexIfMissing(IDbCommand command, string name, string sql)
    {
        try
        {
            command.CommandText = sql;
            command.ExecuteNonQuery();
        }
        catch (Exception ex) when (ex.Message.Contains("ORA-00955", StringComparison.OrdinalIgnoreCase))
        {
            // The index already exists in this database.
        }
    }
}
