using DbUp.Engine;
using System;
using System.Data;

namespace EvnHanoi.Infrastructure.Migrations.IdentityService;

/// <summary>
/// Creates the audit log for requests received from external API consumers.
/// </summary>
public class Migration0043_CreateExternalApiCallLogsTable : IScript
{
    public string ProvideScript(Func<IDbCommand> dbCommandFactory)
    {
        using var command = dbCommandFactory();

        try
        {
            command.CommandText = @"
                CREATE TABLE EXTERNAL_API_CALL_LOGS (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    API_KEY_ID NUMBER NULL,
                    KEY_NAME VARCHAR2(100) NULL,
                    ENDPOINT VARCHAR2(500) NOT NULL,
                    HTTP_METHOD VARCHAR2(10) NOT NULL,
                    REQUEST_QUERY CLOB NULL,
                    REQUEST_IP VARCHAR2(64) NULL,
                    STATUS_CODE NUMBER(3) NULL,
                    IS_SUCCESS NUMBER(1) NOT NULL,
                    DURATION_MS NUMBER(10) NULL,
                    RESPONSE_SUMMARY VARCHAR2(1000) NULL,
                    ERROR_MESSAGE CLOB NULL,
                    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    CONSTRAINT FK_EXTERNAL_API_CALL_LOGS_KEY
                        FOREIGN KEY (API_KEY_ID) REFERENCES EXTERNAL_API_KEYS(ID) ON DELETE SET NULL,
                    CONSTRAINT CK_EXTERNAL_API_CALL_LOGS_SUCCESS CHECK (IS_SUCCESS IN (0, 1))
                )";
            command.ExecuteNonQuery();
        }
        catch (Exception ex) when (ex.Message.Contains("ORA-00955", StringComparison.OrdinalIgnoreCase))
        {
            // The table already exists in this database.
        }

        CreateIndex(command, "IDX_EXTERNAL_API_CALL_LOGS_CREATED_AT", "CREATE INDEX IDX_EXTERNAL_API_CALL_LOGS_CREATED_AT ON EXTERNAL_API_CALL_LOGS(CREATED_AT)");
        CreateIndex(command, "IDX_EXTERNAL_API_CALL_LOGS_API_KEY_ID", "CREATE INDEX IDX_EXTERNAL_API_CALL_LOGS_API_KEY_ID ON EXTERNAL_API_CALL_LOGS(API_KEY_ID)");
        CreateIndex(command, "IDX_EXTERNAL_API_CALL_LOGS_STATUS_CODE", "CREATE INDEX IDX_EXTERNAL_API_CALL_LOGS_STATUS_CODE ON EXTERNAL_API_CALL_LOGS(STATUS_CODE)");

        return string.Empty;
    }

    private static void CreateIndex(IDbCommand command, string name, string sql)
    {
        try
        {
            command.CommandText = sql;
            command.ExecuteNonQuery();
        }
        catch (Exception ex) when (ex.Message.Contains("ORA-00955", StringComparison.OrdinalIgnoreCase))
        {
            // The index already exists.
        }
    }
}
