using DbUp.Engine;
using System;
using System.Data;

namespace EvnHanoi.Infrastructure.Migrations.IdentityService;

/// <summary>
/// Creates the table used to manage private keys for external API consumers.
/// </summary>
public class Migration0040_CreateExternalApiKeysTable : IScript
{
    public string ProvideScript(Func<IDbCommand> dbCommandFactory)
    {
        using var command = dbCommandFactory();

        try
        {
            command.CommandText = @"
                CREATE TABLE EXTERNAL_API_KEYS (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    KEY_NAME VARCHAR2(100) NOT NULL,
                    KEY_HASH VARCHAR2(64) NOT NULL,
                    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
                    EXPIRES_AT TIMESTAMP NULL,
                    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    CREATED_BY VARCHAR2(100) NULL,
                    REVOKED_AT TIMESTAMP NULL,
                    NOTE VARCHAR2(500) NULL,
                    CONSTRAINT UQ_EXTERNAL_API_KEYS_HASH UNIQUE (KEY_HASH),
                    CONSTRAINT CK_EXTERNAL_API_KEYS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
                )";
            command.ExecuteNonQuery();
        }
        catch (Exception ex) when (ex.Message.Contains("ORA-00955", StringComparison.OrdinalIgnoreCase))
        {
            // The table already exists in this database.
        }

        return string.Empty;
    }
}
