using DbUp.Engine;
using System;
using System.Data;

namespace EvnHanoi.Infrastructure.Migrations.IdentityService;

/// <summary>
/// Creates the table backing User Guide Management (Quản lý hướng dẫn sử dụng) —
/// one guide document per role, with the underlying file stored in MinIO
/// (ObjectKey references the object; the binary itself is not stored in Oracle).
/// </summary>
public class Migration0050_CreateUserGuideTable : IScript
{
    public string ProvideScript(Func<IDbCommand> dbCommandFactory)
    {
        using var command = dbCommandFactory();

        try
        {
            command.CommandText = @"
                CREATE TABLE USER_GUIDE (
                    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    RoleName VARCHAR2(200) NOT NULL,
                    FileName VARCHAR2(255) NOT NULL,
                    ObjectKey VARCHAR2(500) NOT NULL,
                    FileSize NUMBER NULL,
                    ContentType VARCHAR2(150) NULL,
                    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                    CreatedBy VARCHAR2(100) NULL,
                    UpdatedAt TIMESTAMP NULL,
                    UpdatedBy VARCHAR2(100) NULL
                )";
            command.ExecuteNonQuery();
        }
        catch (Exception ex) when (ex.Message.Contains("ORA-00955", StringComparison.OrdinalIgnoreCase))
        {
            // The table already exists in this database.
        }

        return string.Empty;
    }
}
