resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: apigateway-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080;8000
    - services__identityservice__http__0=http://identityservice:8080
    - services__equipmentservice__http__0=http://equipmentservice:8080
    - services__digitizationservice__http__0=http://digitizationservice:8080
    - services__notificationservice__http__0=http://notificationservice:8080
    - services__syncservice__http__0=http://syncservice:8080
    - services__workflowservice__http__0=http://workflowservice:8080
    - services__reportservice__http__0=http://reportservice:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=apigateway
    - ASPNETCORE_URLS=http://+:8080;

