---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitizationservice
  labels:
    app: digitizationservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: digitizationservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digitizationservice
    spec:
      containers:
      - name: digitizationservice
        image: harbor.ecoit.vn/x10/backend/digitizationservice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: digitizationservice-env
      terminationGracePeriodSeconds: 180
