-- Script0011_Dynamic_Reports.sql
-- Tạo các bảng cho Nhóm báo cáo và Báo cáo động

CREATE TABLE REPORT_GROUPS (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(255) NOT NULL,
    SortOrder NUMBER DEFAULT 0,
    Description VARCHAR2(1000) NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50)
);

CREATE TABLE DYNAMIC_REPORTS (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GroupId NUMBER NOT NULL,
    Name VARCHAR2(255) NOT NULL,
    SqlQuery CLOB NOT NULL,
    ParametersJson CLOB NULL,
    AllowedRoles VARCHAR2(1000) NULL,
    IsActive NUMBER(1) DEFAULT 1,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50),
    CONSTRAINT fk_dynreport_group FOREIGN KEY (GroupId) REFERENCES REPORT_GROUPS(Id) ON DELETE CASCADE
);

-- Seed data
INSERT INTO REPORT_GROUPS (Name, SortOrder, Description)
VALUES ('Báo cáo thiết bị', 1, 'Các báo cáo liên quan đến quản lý thiết bị và loại thiết bị');

INSERT INTO DYNAMIC_REPORTS (GroupId, Name, SqlQuery, ParametersJson, AllowedRoles, IsActive)
SELECT 
    Id, 
    'Thống kê số lượng thiết bị theo loại', 
    'SELECT et.Name AS "Loại thiết bị", COUNT(e.Id) AS "Số lượng" FROM Equipments e JOIN EquipmentTypes et ON e.EquipmentTypeId = et.Id GROUP BY et.Name', 
    '[]', 
    'ADMIN,USER', 
    1 
FROM REPORT_GROUPS 
WHERE Name = 'Báo cáo thiết bị';

INSERT INTO DYNAMIC_REPORTS (GroupId, Name, SqlQuery, ParametersJson, AllowedRoles, IsActive)
SELECT 
    Id, 
    'Danh sách thiết bị chi tiết', 
    'SELECT e.Id AS "Mã hệ thống", e.Code AS "Mã thiết bị", e.Name AS "Tên thiết bị", e.SerialNumber AS "Số Serial", et.Name AS "Loại thiết bị" FROM Equipments e JOIN EquipmentTypes et ON e.EquipmentTypeId = et.Id WHERE (:Name IS NULL OR e.Name LIKE ''%'' || :Name || ''%'')', 
    '[{"name": "Name", "type": "text", "label": "Tên thiết bị"}]', 
    'ADMIN,USER', 
    1 
FROM REPORT_GROUPS 
WHERE Name = 'Báo cáo thiết bị';
