-- E:\ecoit\sohoax10\sohoa.backend\BuildingBlocks\EvnHanoi.Infrastructure\Migrations\Script0009_Identity_Access_Control.sql
-- Migration bổ sung các bảng cho Gói 1 (Menu), Gói 2 (User Group), Gói 3 (User Unit Role), Gói 5 (Upload Config)

-- 1. Bảng APP_MENU (Gói 1)
CREATE TABLE APP_MENU (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Url VARCHAR2(255) NULL,
    Icon VARCHAR2(50) NULL,
    ParentId NUMBER NULL,
    SortOrder NUMBER DEFAULT 0,
    IsActive NUMBER(1) DEFAULT 1,
    PermissionCode VARCHAR2(100) NULL,
    CONSTRAINT fk_menu_parent FOREIGN KEY (ParentId) REFERENCES APP_MENU(Id) ON DELETE CASCADE
);

-- 2. Bảng USER_GROUP (Gói 2)
CREATE TABLE USER_GROUP (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Description VARCHAR2(255) NULL,
    IsActive NUMBER(1) DEFAULT 1
);

-- 3. Bảng USER_GROUP_MEMBER (Gói 2)
CREATE TABLE USER_GROUP_MEMBER (
    UserGroupId NUMBER NOT NULL,
    UserId NUMBER NOT NULL,
    PRIMARY KEY (UserGroupId, UserId),
    CONSTRAINT fk_ugm_group FOREIGN KEY (UserGroupId) REFERENCES USER_GROUP(Id) ON DELETE CASCADE,
    CONSTRAINT fk_ugm_user FOREIGN KEY (UserId) REFERENCES APP_USER(Id) ON DELETE CASCADE
);

-- 4. Bảng USER_GROUP_ROLE (Gói 2)
CREATE TABLE USER_GROUP_ROLE (
    UserGroupId NUMBER NOT NULL,
    RoleId NUMBER NOT NULL,
    PRIMARY KEY (UserGroupId, RoleId),
    CONSTRAINT fk_ugr_group FOREIGN KEY (UserGroupId) REFERENCES USER_GROUP(Id) ON DELETE CASCADE,
    CONSTRAINT fk_ugr_role FOREIGN KEY (RoleId) REFERENCES ROLE(Id) ON DELETE CASCADE
);

-- 5. Bảng USER_UNIT_ROLE (Gói 3)
CREATE TABLE USER_UNIT_ROLE (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId NUMBER NOT NULL,
    UnitId NUMBER NOT NULL,
    RoleId NUMBER NOT NULL,
    CONSTRAINT fk_uur_user FOREIGN KEY (UserId) REFERENCES APP_USER(Id) ON DELETE CASCADE,
    CONSTRAINT fk_uur_unit FOREIGN KEY (UnitId) REFERENCES ORGANIZATION_UNIT(Id) ON DELETE CASCADE,
    CONSTRAINT fk_uur_role FOREIGN KEY (RoleId) REFERENCES ROLE(Id) ON DELETE CASCADE,
    CONSTRAINT uq_uur_user_unit_role UNIQUE (UserId, UnitId, RoleId)
);

-- 6. Bảng UPLOAD_CONFIG (Gói 5)
CREATE TABLE UPLOAD_CONFIG (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ModuleCode VARCHAR2(50) NOT NULL UNIQUE,
    AllowedExtensions VARCHAR2(255) NOT NULL,
    MaxSizeMb NUMBER DEFAULT 10 NOT NULL,
    Description VARCHAR2(255) NULL
);

-- Seed dữ liệu cho APP_MENU
INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (1, 'Bảng điều khiển', '/dashboard', 'pi pi-home', NULL, 1, 1, 'VIEW_DASHBOARD');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (2, 'Quản trị hệ thống', NULL, 'pi pi-cog', NULL, 2, 1, 'USER_MANAGE');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (3, 'Người dùng', '/administration/user-management', 'pi pi-users', 2, 1, 1, 'USER_MANAGE');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (4, 'Vai trò & Quyền', '/administration/role-management', 'pi pi-key', 2, 2, 1, 'ROLE_MANAGE');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (5, 'Cấu hình Menu', '/administration/menu-management', 'pi pi-list', 2, 3, 1, 'MENU_MANAGE');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (6, 'Nhóm người dùng', '/administration/user-groups', 'pi pi-user-plus', 2, 4, 1, 'USER_GROUP_MANAGE');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (7, 'Cấu hình Upload', '/administration/upload-configuration', 'pi pi-upload', 2, 5, 1, 'UPLOAD_CONFIG_MANAGE');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (8, 'Cơ cấu tổ chức', '/administration/organization-settings', 'pi pi-sitemap', 2, 6, 1, 'ORGANIZATION_MANAGE');

INSERT INTO APP_MENU (Id, Name, Url, Icon, ParentId, SortOrder, IsActive, PermissionCode)
VALUES (9, 'Nhật ký hệ thống', '/administration/audit-log', 'pi pi-history', 2, 7, 1, 'AUDIT_LOG_VIEW');

-- Bổ sung quyền mới vào hệ thống cho vai trò ADMIN
INSERT INTO ROLE_PERMISSION (Id, RoleId, PermissionCode)
SELECT 'p8', Id, 'MENU_MANAGE' FROM ROLE WHERE Code = 'ADMIN';

INSERT INTO ROLE_PERMISSION (Id, RoleId, PermissionCode)
SELECT 'p9', Id, 'USER_GROUP_MANAGE' FROM ROLE WHERE Code = 'ADMIN';

INSERT INTO ROLE_PERMISSION (Id, RoleId, PermissionCode)
SELECT 'p10', Id, 'UPLOAD_CONFIG_MANAGE' FROM ROLE WHERE Code = 'ADMIN';

INSERT INTO ROLE_PERMISSION (Id, RoleId, PermissionCode)
SELECT 'p11', Id, 'AUDIT_LOG_VIEW' FROM ROLE WHERE Code = 'ADMIN';

INSERT INTO ROLE_PERMISSION (Id, RoleId, PermissionCode)
SELECT 'p12', Id, 'AUDIT_LOG_DELETE' FROM ROLE WHERE Code = 'ADMIN';

-- Seed cấu hình upload mặc định cho UPLOAD_CONFIG
INSERT INTO UPLOAD_CONFIG (ModuleCode, AllowedExtensions, MaxSizeMb, Description)
VALUES ('EQUIPMENT_ATTACHMENT', '.pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg', 50, 'Tài liệu đính kèm thiết bị');

INSERT INTO UPLOAD_CONFIG (ModuleCode, AllowedExtensions, MaxSizeMb, Description)
VALUES ('DIGITIZATION_SCAN', '.pdf,.png,.jpg,.jpeg', 100, 'File quét số hóa hồ sơ');
