-- ============================================================================
-- BẢN SQL DỰ PHÒNG cho Migrations/DigitizationService/0003_FileAttachmentIdToVarchar36.cs
-- ============================================================================
-- KHÔNG chạy tự động. Đặt ở Migrations/Manual/ là CÓ Ý:
--   * DatabaseMigrationHelper nạp script theo filter name.Contains(".Migrations.<Service>.")
--     nên tên resource "...Migrations.Manual.DigitizationService_0003_..." KHÔNG khớp
--     -> DbUp bỏ qua file này, không có nguy cơ chạy trùng với bản .cs.
--   * Không thể đặt bản .sql vào thẳng Migrations/DigitizationService/: helper dùng
--     OracleDatabaseWithSemicolonDelimiter, nó cắt script theo ';' nên mọi khối PL/SQL
--     (DECLARE/BEGIN/EXCEPTION/EXECUTE IMMEDIATE) bị xé thành câu lệnh rời và chết
--     ORA-06550 — ĐÃ THỬ VÀ XÁC NHẬN 2026-08-11. Mà không có PL/SQL thì không viết được
--     điều kiện, ALTER trần sẽ ném ORA-30673/ORA-01430 trên DB đã đổi kiểu từ trước và
--     làm DbUp dừng ngay lúc service khởi động.
--
-- KHI NÀO DÙNG: bản .cs không chạy được (DbUp lỗi, cần vá gấp bằng tay, hoặc DBA muốn
-- xem/áp dụng thay đổi ngoài luồng deploy).
--
-- CÁCH CHẠY (sqlplus xử lý PL/SQL bình thường, kết thúc bằng dấu '/'):
--   sqlplus <user>/<pass>@<host>:1521/<service> @DigitizationService_0003_FileAttachmentIdToVarchar36.sql
-- Sau khi chạy tay, nhớ ghi journal để bản .cs không chạy lại (tên script đúng như DbUp đặt):
--   INSERT INTO SCHEMAVERSIONS (SCRIPTNAME, APPLIED)
--   VALUES ('EvnHanoi.Infrastructure.Migrations.DigitizationService.Migration0003_FileAttachmentIdToVarchar36.cs', SYSTIMESTAMP);
--   COMMIT;
--   (kiểm tra tên cột của bảng SCHEMAVERSIONS trước khi insert — DbUp tạo SCRIPTNAME/APPLIED.)
--
-- NỘI DUNG: 0001_Schema.sql tạo FILE_ATTACHMENT.ID = NUMBER GENERATED BY DEFAULT AS IDENTITY
-- và FOLDER_DOCUMENTS.DOCUMENTID = NUMBER, nhưng toàn bộ code C# coi khoá này là Guid
-- (FileAttachment.Id, AddDocumentToFolderAsync(long, Guid), OcrTaskMessage.FileId) nên mọi
-- INSERT đều chết ORA-01722. Script đổi 2 cột sang VARCHAR2(36) theo quy ước khoá chính của
-- project (BACKEND_GUIDELINES.md §2) và dựng lại FK_FOLDER_DOC_DOC. Idempotent: chạy lại
-- trên DB đã đổi kiểu thì không làm gì.
--
-- ROLLBACK: xem doc comment trong 0003_FileAttachmentIdToVarchar36.cs.
-- ============================================================================
SET SERVEROUTPUT ON

BEGIN
    -- 1. Bỏ FK trước khi đổi kiểu 2 cột hai đầu quan hệ.
    FOR c IN (
        SELECT 1
        FROM user_tab_cols
        WHERE table_name = 'FOLDER_DOCUMENTS'
          AND column_name = 'DOCUMENTID'
          AND data_type = 'NUMBER'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE FOLDER_DOCUMENTS DROP CONSTRAINT FK_FOLDER_DOC_DOC';
            DBMS_OUTPUT.PUT_LINE('Đã bỏ FK_FOLDER_DOC_DOC');
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2443 THEN RAISE; END IF;  -- -2443: constraint không tồn tại
                DBMS_OUTPUT.PUT_LINE('FK_FOLDER_DOC_DOC không tồn tại, bỏ qua');
        END;
    END LOOP;

    -- 2. Cột IDENTITY không đổi được kiểu khi còn thuộc tính identity.
    FOR c IN (
        SELECT 1
        FROM user_tab_cols
        WHERE table_name = 'FILE_ATTACHMENT'
          AND column_name = 'ID'
          AND identity_column = 'YES'
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE FILE_ATTACHMENT MODIFY ID DROP IDENTITY';
        DBMS_OUTPUT.PUT_LINE('Đã bỏ IDENTITY của FILE_ATTACHMENT.ID');
    END LOOP;

    -- 3. Đổi kiểu FILE_ATTACHMENT.ID -> VARCHAR2(36).
    FOR c IN (
        SELECT 1
        FROM user_tab_cols
        WHERE table_name = 'FILE_ATTACHMENT'
          AND column_name = 'ID'
          AND data_type = 'NUMBER'
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE FILE_ATTACHMENT MODIFY (ID VARCHAR2(36))';
        DBMS_OUTPUT.PUT_LINE('FILE_ATTACHMENT.ID -> VARCHAR2(36)');
    END LOOP;

    -- 4. Đổi kiểu FOLDER_DOCUMENTS.DOCUMENTID -> VARCHAR2(36).
    FOR c IN (
        SELECT 1
        FROM user_tab_cols
        WHERE table_name = 'FOLDER_DOCUMENTS'
          AND column_name = 'DOCUMENTID'
          AND data_type = 'NUMBER'
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE FOLDER_DOCUMENTS MODIFY (DOCUMENTID VARCHAR2(36))';
        DBMS_OUTPUT.PUT_LINE('FOLDER_DOCUMENTS.DOCUMENTID -> VARCHAR2(36)');
    END LOOP;

    -- 5. Dựng lại FK nếu đang thiếu.
    FOR c IN (
        SELECT 1
        FROM user_tab_cols f
        WHERE f.table_name = 'FOLDER_DOCUMENTS'
          AND f.column_name = 'DOCUMENTID'
          AND f.data_type = 'VARCHAR2'
          AND NOT EXISTS (
              SELECT 1 FROM user_constraints
              WHERE constraint_name = 'FK_FOLDER_DOC_DOC'
                AND table_name = 'FOLDER_DOCUMENTS'
          )
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE FOLDER_DOCUMENTS ADD CONSTRAINT FK_FOLDER_DOC_DOC '
                       || 'FOREIGN KEY (DOCUMENTID) REFERENCES FILE_ATTACHMENT(ID) ON DELETE CASCADE';
        DBMS_OUTPUT.PUT_LINE('Đã dựng lại FK_FOLDER_DOC_DOC');
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Hoàn tất.');
END;
/
