-- ============================================================================
-- BẢN SQL DỰ PHÒNG cho Migrations/IdentityService/Migration0055_CreateSsoLoginHistoryTable.cs
-- Bao gồm phần bổ sung RESOURCE_NAME của Migration0056_AddSsoHistoryResourceName.cs.
-- ============================================================================
-- KHÔNG chạy tự động: thư mục Migrations/Manual không khớp bộ lọc migration của DbUp.
-- Chạy trong schema chứa APP_USER bằng SQL*Plus hoặc SQL Developer (Run Script/F5).
-- CÁCH CHẠY:
--   sqlplus <user>/<pass>@<host>:1521/<service> @IdentityService_0055_CreateSsoLoginHistoryTable.sql
--
-- NỘI DUNG: tạo bảng lịch sử đăng nhập SSO, khóa ngoại tới APP_USER và 3 index.
-- Chạy lại sẽ bỏ qua bảng/index đã tồn tại; bổ sung RESOURCE_NAME nếu bảng cũ thiếu cột.
-- Không thêm dữ liệu mẫu, không xóa lịch sử đang có.
-- LOGIN_AT/CREATED_AT được ứng dụng ghi bằng giờ UTC.
-- Oracle DDL tự commit; ROLLBACK không hoàn tác CREATE/ALTER TABLE.
--
-- JOURNAL (tùy chọn, chỉ ghi sau khi script chạy thành công và kiểm tra schema):
-- Các migration .cs tương ứng có thể chạy lại an toàn nếu chưa ghi journal.
-- Kiểm tra tên cột SCHEMAVERSIONS trước khi thực hiện các lệnh sau:
--   INSERT INTO SCHEMAVERSIONS (SCRIPTNAME, APPLIED)
--   SELECT 'EvnHanoi.Infrastructure.Migrations.IdentityService.Migration0055_CreateSsoLoginHistoryTable.cs', SYSTIMESTAMP
--   FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SCHEMAVERSIONS
--     WHERE SCRIPTNAME = 'EvnHanoi.Infrastructure.Migrations.IdentityService.Migration0055_CreateSsoLoginHistoryTable.cs');
--   INSERT INTO SCHEMAVERSIONS (SCRIPTNAME, APPLIED)
--   SELECT 'EvnHanoi.Infrastructure.Migrations.IdentityService.Migration0056_AddSsoHistoryResourceName.cs', SYSTIMESTAMP
--   FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SCHEMAVERSIONS
--     WHERE SCRIPTNAME = 'EvnHanoi.Infrastructure.Migrations.IdentityService.Migration0056_AddSsoHistoryResourceName.cs');
--   COMMIT;
--
-- ROLLBACK thủ công cho bảng vừa tạo (sẽ mất toàn bộ lịch sử, cần sao lưu trước):
--   DROP TABLE SSO_LOGIN_HISTORY;
--   DELETE FROM SCHEMAVERSIONS WHERE SCRIPTNAME IN (
--     'EvnHanoi.Infrastructure.Migrations.IdentityService.Migration0055_CreateSsoLoginHistoryTable.cs',
--     'EvnHanoi.Infrastructure.Migrations.IdentityService.Migration0056_AddSsoHistoryResourceName.cs');
--   COMMIT;
-- ============================================================================
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    v_exists NUMBER;

    PROCEDURE create_index_if_missing(p_name VARCHAR2, p_sql VARCHAR2) IS
        v_index_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_index_exists FROM user_indexes WHERE index_name = p_name;
        IF v_index_exists = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('Da tao index ' || p_name || '.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Index ' || p_name || ' da ton tai, bo qua.');
        END IF;
    END;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM user_tables WHERE table_name = 'SSO_LOGIN_HISTORY';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE SSO_LOGIN_HISTORY (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                USER_ID VARCHAR2(36) NULL,
                USERNAME VARCHAR2(200) NOT NULL,
                FULL_NAME VARCHAR2(255) NULL,
                ACTION VARCHAR2(50) DEFAULT ''SSO_LOGIN'' NOT NULL,
                RESOURCE_TYPE VARCHAR2(100) DEFAULT ''SSO'' NOT NULL,
                RESOURCE_NAME VARCHAR2(255) DEFAULT ''Cổng SSO EVNHANOI'' NULL,
                LOGIN_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                DETAILS CLOB NULL,
                IP_ADDRESS VARCHAR2(64) NULL,
                STATUS_CODE NUMBER(5) NULL,
                IS_SUCCESS NUMBER(1) DEFAULT 1 NOT NULL,
                IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT FK_SSO_LOGIN_HISTORY_USER
                    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID) ON DELETE SET NULL,
                CONSTRAINT CK_SSO_LOGIN_HISTORY_SUCCESS CHECK (IS_SUCCESS IN (0, 1)),
                CONSTRAINT CK_SSO_LOGIN_HISTORY_DELETED CHECK (IS_DELETED IN (0, 1))
            )';
        DBMS_OUTPUT.PUT_LINE('Da tao bang SSO_LOGIN_HISTORY.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Bang SSO_LOGIN_HISTORY da ton tai, bo qua CREATE TABLE.');
    END IF;

    SELECT COUNT(*) INTO v_exists FROM user_tab_columns
    WHERE table_name = 'SSO_LOGIN_HISTORY' AND column_name = 'RESOURCE_NAME';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SSO_LOGIN_HISTORY ADD (RESOURCE_NAME VARCHAR2(255) DEFAULT ''Cổng SSO EVNHANOI'' NULL)';
        DBMS_OUTPUT.PUT_LINE('Da bo sung cot RESOURCE_NAME.');
    END IF;

    create_index_if_missing('IDX_SSO_LOGIN_HISTORY_LOGIN_AT',
        'CREATE INDEX IDX_SSO_LOGIN_HISTORY_LOGIN_AT ON SSO_LOGIN_HISTORY(LOGIN_AT)');
    create_index_if_missing('IDX_SSO_LOGIN_HISTORY_USERNAME',
        'CREATE INDEX IDX_SSO_LOGIN_HISTORY_USERNAME ON SSO_LOGIN_HISTORY(USERNAME)');
    create_index_if_missing('IDX_SSO_LOGIN_HISTORY_USER_ID',
        'CREATE INDEX IDX_SSO_LOGIN_HISTORY_USER_ID ON SSO_LOGIN_HISTORY(USER_ID)');
END;
/

-- KIỂM TRA:
SELECT column_name, data_type, data_length, nullable
FROM user_tab_columns WHERE table_name = 'SSO_LOGIN_HISTORY' ORDER BY column_id;

SELECT index_name, column_name, column_position
FROM user_ind_columns WHERE table_name = 'SSO_LOGIN_HISTORY'
ORDER BY index_name, column_position;

SELECT constraint_name, constraint_type, status
FROM user_constraints WHERE table_name = 'SSO_LOGIN_HISTORY';
