-- Migration to add Workflow Instance, Task and History tables for Linear Execution

CREATE TABLE WORKFLOWINSTANCES (
    ID                     VARCHAR2(36)  NOT NULL PRIMARY KEY,
    WORKFLOWDEFINITIONID  VARCHAR2(36)  NOT NULL,
    TARGETENTITYID        VARCHAR2(50)  NOT NULL,
    TARGETENTITYTYPE      VARCHAR2(50)  NOT NULL,
    STATUS                VARCHAR2(50)  DEFAULT 'Running' NOT NULL,
    CURRENTSTEPORDER      NUMBER        DEFAULT 1 NOT NULL,
    CREATEDAT             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT             TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_WFINST_WFDEF FOREIGN KEY (WORKFLOWDEFINITIONID) REFERENCES WORKFLOWDEFINITIONS(ID) ON DELETE CASCADE
);

CREATE TABLE WORKFLOWTASKS (
    ID                  VARCHAR2(36)  NOT NULL PRIMARY KEY,
    WORKFLOWINSTANCEID  VARCHAR2(36)  NOT NULL,
    STEPID              VARCHAR2(36)  NOT NULL,
    STEPNAME            VARCHAR2(255) NOT NULL,
    ASSIGNEDROLE        VARCHAR2(100) NOT NULL,
    ASSIGNEEUSERID      VARCHAR2(50)  NULL,
    STATUS              VARCHAR2(50)  DEFAULT 'Pending' NOT NULL,
    CREATEDAT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETEDAT         TIMESTAMP     NULL,
    CONSTRAINT FK_WFTASK_WFINST FOREIGN KEY (WORKFLOWINSTANCEID) REFERENCES WORKFLOWINSTANCES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WFTASK_WFSTEP FOREIGN KEY (STEPID) REFERENCES WORKFLOWSTEPS(ID) ON DELETE CASCADE
);

CREATE TABLE WORKFLOWHISTORY (
    ID                  VARCHAR2(36)  NOT NULL PRIMARY KEY,
    WORKFLOWINSTANCEID  VARCHAR2(36)  NOT NULL,
    STEPNAME            VARCHAR2(255) NOT NULL,
    ACTION              VARCHAR2(50)  NOT NULL,
    ACTIONBYUSERID      VARCHAR2(50)  NOT NULL,
    "Comment"           VARCHAR2(1000) NULL,
    ACTIONDATE          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_WFHIST_WFINST FOREIGN KEY (WORKFLOWINSTANCEID) REFERENCES WORKFLOWINSTANCES(ID) ON DELETE CASCADE
);
