-- Migration to add Workflow Instance Node State and denormalized Borrow Record Status columns

ALTER TABLE WORKFLOWINSTANCES ADD CURRENTNODEID VARCHAR2(50) NULL;
ALTER TABLE WORKFLOWINSTANCES ADD CURRENTNODENAME NVARCHAR2(255) NULL;

ALTER TABLE BORROWRECORDS ADD WORKFLOWINSTANCEID VARCHAR2(36) NULL;
ALTER TABLE BORROWRECORDS ADD WORKFLOWSTATUSNAME NVARCHAR2(255) NULL;

ALTER TABLE BORROWRECORDS ADD CONSTRAINT FK_BORROW_WFINST FOREIGN KEY (WORKFLOWINSTANCEID) REFERENCES WORKFLOWINSTANCES(ID) ON DELETE SET NULL;
