-- Consolidated Equipment Service Schema

CREATE TABLE PHYSICAL_FONDS (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Code VARCHAR2(50) NOT NULL UNIQUE,
    Name VARCHAR2(255) NOT NULL,
    Description VARCHAR2(1000) NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50)
);

CREATE TABLE PHYSICAL_SHELF (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FondsId NUMBER NOT NULL,
    Code VARCHAR2(50) NOT NULL,
    Name VARCHAR2(255) NOT NULL,
    Description VARCHAR2(1000) NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50),
    CONSTRAINT fk_phys_shelf_fonds FOREIGN KEY (FondsId) REFERENCES PHYSICAL_FONDS(Id)
);

CREATE TABLE PHYSICAL_FLOOR (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ShelfId NUMBER NOT NULL,
    Code VARCHAR2(50) NOT NULL,
    Name VARCHAR2(255) NOT NULL,
    Description VARCHAR2(1000) NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50),
    CONSTRAINT fk_phys_floor_shelf FOREIGN KEY (ShelfId) REFERENCES PHYSICAL_SHELF(Id)
);

CREATE TABLE PHYSICAL_BOX (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FloorId NUMBER NOT NULL,
    Code VARCHAR2(50) NOT NULL,
    Name VARCHAR2(255) NOT NULL,
    Description VARCHAR2(1000) NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50),
    CONSTRAINT fk_phys_box_floor FOREIGN KEY (FloorId) REFERENCES PHYSICAL_FLOOR(Id)
);

CREATE TABLE CATALOG (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Code VARCHAR2(50) NOT NULL UNIQUE,
    Name VARCHAR2(255) NOT NULL,
    CatalogType VARCHAR2(50) DEFAULT 'System' NOT NULL,
    ParentId NUMBER NULL,
    Description VARCHAR2(1000) NULL,
    UnitId NUMBER NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR2(50),
    UpdatedAt TIMESTAMP,
    UpdatedBy VARCHAR2(50),
    CONSTRAINT fk_catalog_parent FOREIGN KEY (ParentId) REFERENCES CATALOG(Id)
);

CREATE TABLE EavFormTemplates (
    Id           VARCHAR2(36)  NOT NULL PRIMARY KEY,
    Name         VARCHAR2(255) NOT NULL,
    Code         VARCHAR2(50)  NULL,
    Category     VARCHAR2(50)  NULL,
    Description  VARCHAR2(1000) NULL,
    FormSchema   CLOB          NOT NULL,
    Version      NUMBER        DEFAULT 1 NOT NULL,
    IsActive     NUMBER(1)     DEFAULT 1 NOT NULL,
    CreatedAt    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CreatedBy    VARCHAR2(50)  NULL
);

CREATE TABLE EquipmentTypes (
    Id           VARCHAR2(36)   NOT NULL PRIMARY KEY,
    Name         VARCHAR2(255)  NOT NULL,
    Code         VARCHAR2(100)  NOT NULL UNIQUE,
    Description  VARCHAR2(1000) NULL,
    CreatedAt    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UpdatedAt    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE AttributeDefinitions (
    Id                VARCHAR2(36)   NOT NULL PRIMARY KEY,
    EquipmentTypeId   VARCHAR2(36)   NOT NULL,
    Name              VARCHAR2(255)  NOT NULL,
    Code              VARCHAR2(100)  NOT NULL,
    DataType          VARCHAR2(50)   NOT NULL,
    IsRequired        NUMBER(1)      DEFAULT 0 NOT NULL,
    CONSTRAINT fk_attrdef_eqtype FOREIGN KEY (EquipmentTypeId) REFERENCES EquipmentTypes(Id) ON DELETE CASCADE
);

CREATE TABLE Equipments (
    Id               VARCHAR2(36)   NOT NULL PRIMARY KEY,
    EquipmentTypeId  VARCHAR2(36)   NOT NULL,
    Name             VARCHAR2(255)  NOT NULL,
    Code             VARCHAR2(100)  NOT NULL UNIQUE,
    SerialNumber     VARCHAR2(100)  NULL,
    UnitId           NUMBER         NULL,
    CreatedAt        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy        VARCHAR2(100)  NULL,
    RowVersion       NUMBER         DEFAULT 1 NOT NULL,
    CONSTRAINT fk_equip_eqtype FOREIGN KEY (EquipmentTypeId) REFERENCES EquipmentTypes(Id)
);

CREATE TABLE AttributeValues (
    Id                     VARCHAR2(36)   NOT NULL PRIMARY KEY,
    EquipmentId            VARCHAR2(36)   NOT NULL,
    AttributeDefinitionId  VARCHAR2(36)   NOT NULL,
    Value                  CLOB           NULL,
    CONSTRAINT fk_attrval_equip FOREIGN KEY (EquipmentId) REFERENCES Equipments(Id) ON DELETE CASCADE,
    CONSTRAINT fk_attrval_def FOREIGN KEY (AttributeDefinitionId) REFERENCES AttributeDefinitions(Id) ON DELETE CASCADE
);

CREATE TABLE Dossiers (
    Id           VARCHAR2(36)   NOT NULL PRIMARY KEY,
    EquipmentId  VARCHAR2(36)   NULL,
    Title        VARCHAR2(255)  NOT NULL,
    Description  VARCHAR2(1000) NULL,
    Status       VARCHAR2(50)   DEFAULT 'Draft' NOT NULL,
    Version      NUMBER         DEFAULT 1 NOT NULL,
    UnitId       NUMBER         NULL,
    CreatedAt    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy    VARCHAR2(100)  NULL,
    UpdatedAt    TIMESTAMP      NULL,
    UpdatedBy    VARCHAR2(100)  NULL,
    RowVersion   NUMBER         DEFAULT 1 NOT NULL,
    CONSTRAINT fk_dossier_equip FOREIGN KEY (EquipmentId) REFERENCES Equipments(Id) ON DELETE SET NULL
);

CREATE TABLE DossierVersions (
    Id             VARCHAR2(36)   NOT NULL PRIMARY KEY,
    DossierId      VARCHAR2(36)   NOT NULL,
    VersionNumber  NUMBER         NOT NULL,
    Title          VARCHAR2(255)  NOT NULL,
    Description    VARCHAR2(1000) NULL,
    Status         VARCHAR2(50)   NOT NULL,
    ChangeLog      VARCHAR2(1000) NULL,
    CreatedAt      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CreatedBy      VARCHAR2(100)  NULL,
    CONSTRAINT fk_dossver_dossier FOREIGN KEY (DossierId) REFERENCES Dossiers(Id) ON DELETE CASCADE
);
