-- DbUp migration script: Create Document Management tables
-- Schema: FOLDERS, DOCUMENTS, DOCUMENT_VERSIONS, DOCUMENT_SIGNATURES

-- ===== TABLE FOLDERS =====
CREATE TABLE FOLDERS (
    ID VARCHAR2(36) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    PARENT_ID VARCHAR2(36),
    UNIT_ID NUMBER NOT NULL,
    ROW_VERSION NUMBER DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(100),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_DATE TIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_FOLDERS_PARENT FOREIGN KEY (PARENT_ID) REFERENCES FOLDERS(ID),
    CONSTRAINT FK_FOLDERS_ORGANIZATION_UNIT FOREIGN KEY (UNIT_ID) REFERENCES ORGANIZATION_UNIT(ID)
);

CREATE INDEX IDX_FOLDERS_UNIT_ID ON FOLDERS(UNIT_ID);
CREATE INDEX IDX_FOLDERS_PARENT_ID ON FOLDERS(PARENT_ID);
CREATE INDEX IDX_FOLDERS_IS_DELETED ON FOLDERS(IS_DELETED);

-- ===== TABLE DOCUMENTS =====
CREATE TABLE DOCUMENTS (
    ID VARCHAR2(36) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    FOLDER_ID VARCHAR2(36),
    DOSSIER_ID VARCHAR2(36),
    ROW_VERSION NUMBER DEFAULT 1 NOT NULL,
    CREATED_BY VARCHAR2(100),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_DATE TIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DOCUMENTS_FOLDER FOREIGN KEY (FOLDER_ID) REFERENCES FOLDERS(ID),
    CONSTRAINT FK_DOCUMENTS_DOSSIER FOREIGN KEY (DOSSIER_ID) REFERENCES DOSSIERS(ID)
);

CREATE INDEX IDX_DOCUMENTS_FOLDER_ID ON DOCUMENTS(FOLDER_ID);
CREATE INDEX IDX_DOCUMENTS_DOSSIER_ID ON DOCUMENTS(DOSSIER_ID);
CREATE INDEX IDX_DOCUMENTS_IS_DELETED ON DOCUMENTS(IS_DELETED);

-- ===== TABLE DOCUMENT_VERSIONS =====
CREATE TABLE DOCUMENT_VERSIONS (
    ID VARCHAR2(36) PRIMARY KEY,
    DOCUMENT_ID VARCHAR2(36) NOT NULL,
    VERSION_NUMBER NUMBER NOT NULL,
    UPLOAD_SOURCE NUMBER NOT NULL,
    FILE_PATH VARCHAR2(500),
    FILE_SIZE NUMBER,
    MIME_TYPE VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DOCUMENT_VERSIONS_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(ID),
    CONSTRAINT UQ_DOCUMENT_VERSIONS_VERSION UNIQUE (DOCUMENT_ID, VERSION_NUMBER)
);

CREATE INDEX IDX_DOCUMENT_VERSIONS_DOCUMENT_ID ON DOCUMENT_VERSIONS(DOCUMENT_ID);
CREATE INDEX IDX_DOCUMENT_VERSIONS_IS_DELETED ON DOCUMENT_VERSIONS(IS_DELETED);

-- ===== TABLE DOCUMENT_SIGNATURES =====
CREATE TABLE DOCUMENT_SIGNATURES (
    ID VARCHAR2(36) PRIMARY KEY,
    VERSION_ID VARCHAR2(36) NOT NULL,
    SIGNER_NAME VARCHAR2(255),
    SIGN_DATE TIMESTAMP,
    ISSUER VARCHAR2(255),
    IS_VALID NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_DOCUMENT_SIGNATURES_VERSION FOREIGN KEY (VERSION_ID) REFERENCES DOCUMENT_VERSIONS(ID)
);

CREATE INDEX IDX_DOCUMENT_SIGNATURES_VERSION_ID ON DOCUMENT_SIGNATURES(VERSION_ID);

