-- DbUp migration script: Create File Upload System tables
-- Schema: UPLOAD_SESSIONS

-- ===== TABLE UPLOAD_SESSIONS =====
-- Track chunked uploads and file versioning
CREATE TABLE UPLOAD_SESSIONS (
    ID VARCHAR2(36) PRIMARY KEY,
    UPLOAD_ID VARCHAR2(100) NOT NULL UNIQUE,
    FOLDER_ID VARCHAR2(36) NOT NULL,
    FILE_NAME VARCHAR2(500) NOT NULL,
    TOTAL_CHUNKS NUMBER NOT NULL,
    COMPLETED_CHUNKS NUMBER DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(50) DEFAULT 'InProgress' NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100),
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_DATE TIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_UPLOAD_SESSION_FOLDER FOREIGN KEY (FOLDER_ID) REFERENCES FOLDERS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_UPLOAD_SESSIONS_EXPIRES_AT ON UPLOAD_SESSIONS(EXPIRES_AT);
CREATE INDEX IDX_UPLOAD_SESSIONS_STATUS ON UPLOAD_SESSIONS(STATUS);
CREATE INDEX IDX_UPLOAD_SESSIONS_FOLDER_ID ON UPLOAD_SESSIONS(FOLDER_ID);
CREATE INDEX IDX_UPLOAD_SESSIONS_IS_DELETED ON UPLOAD_SESSIONS(IS_DELETED);

-- ===== ALTER DOCUMENTS TABLE =====
-- Add STATUS column to track document state
ALTER TABLE DOCUMENTS ADD STATUS VARCHAR2(50) DEFAULT 'Active' NOT NULL;

-- ===== ALTER DOCUMENT_VERSIONS TABLE =====
-- Add columns for upload tracking and file integrity
ALTER TABLE DOCUMENT_VERSIONS ADD FILE_HASH VARCHAR2(64);
ALTER TABLE DOCUMENT_VERSIONS ADD UPLOAD_SESSION_ID VARCHAR2(36);
ALTER TABLE DOCUMENT_VERSIONS ADD CHUNKS_COUNT NUMBER DEFAULT 1 NOT NULL;

-- Add foreign key for upload session
ALTER TABLE DOCUMENT_VERSIONS 
ADD CONSTRAINT FK_DOCUMENT_VERSIONS_SESSION 
FOREIGN KEY (UPLOAD_SESSION_ID) REFERENCES UPLOAD_SESSIONS(ID) ON DELETE SET NULL;

-- Add index for uploaded session lookup
CREATE INDEX IDX_DOCUMENT_VERSIONS_SESSION_ID ON DOCUMENT_VERSIONS(UPLOAD_SESSION_ID);
