-- Migration to create INFRASTRUCTURE_TYPE and INFRASTRUCTURE tables

CREATE TABLE INFRASTRUCTURE_TYPE (
    ID NUMBER NOT NULL PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

INSERT INTO INFRASTRUCTURE_TYPE (ID, NAME) VALUES (1, 'Trạm biến áp');
INSERT INTO INFRASTRUCTURE_TYPE (ID, NAME) VALUES (2, 'Đường dây');

CREATE TABLE INFRASTRUCTURE (
    ID VARCHAR2(36) NOT NULL PRIMARY KEY,
    CODE VARCHAR2(100) NOT NULL UNIQUE,
    NAME VARCHAR2(255) NOT NULL,
    ADDRESS VARCHAR2(255) NULL,
    INFRA_TYPE_ID NUMBER NOT NULL,
    UNIT_ID NUMBER NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CreatedBy VARCHAR2(100) NULL,
    CreatedDate TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy VARCHAR2(100) NULL,
    ModifiedDate TIMESTAMP NULL,
    IsDeleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_infra_type FOREIGN KEY (INFRA_TYPE_ID) REFERENCES INFRASTRUCTURE_TYPE(ID),
    CONSTRAINT fk_infra_unit FOREIGN KEY (UNIT_ID) REFERENCES ORGANIZATION_UNIT(Id) ON DELETE SET NULL
);
