-- Migration to create DOSSIER_TYPES table

CREATE TABLE DOSSIER_TYPES (
    ID VARCHAR2(36) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    CODE VARCHAR2(100) NOT NULL UNIQUE,
    FORM_ID VARCHAR2(36) NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    PIORITY NUMBER NULL,
    CreatedBy VARCHAR2(100) NULL,
    CreatedDate TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ModifiedBy VARCHAR2(100) NULL,
    ModifiedDate TIMESTAMP NULL,
    IsDeleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_dossiertype_form FOREIGN KEY (FORM_ID) REFERENCES EavFormTemplates(Id) ON DELETE SET NULL
);
